- hosts: all
  name: ensure python is installed for ansible
  user: ubuntu
  gather_facts: false
  pre_tasks:
      - name: update apt-get
        raw: sudo apt-get update
      - name: install python for ansible
        raw: sudo apt-get -y install python-simplejson

- hosts: local
  name: configure server
  user: ubuntu
  gather_facts: true
  vars:
    project_name: 'nurax'
    keys_to_add:
      - https://github.com/hardyoyo.keys
    db_user: 'hyrax'
    db_pass: 'hyrax'
  roles:
    - { role: packages }
    - { role: set_timezone, timezone: America/Los_Angeles }
    - { role: ruby, ruby_version: '2.4.2', ruby_sha_256: '93b9e75e00b262bc4def6b26b7ae8717efc252c47154abb7392e54357e6c8c9c' }
    - { role: fits, fits_version: '0.8.4' }
    - { role: imagemagick, imagemagick_ver: '7.0.7', gs_ver: '9.19', openjpg_ver: '2.1.0', libtiff_ver: '4.0.5', libpng_ver: '1.6.28' }
    - { role: ffmpeg, ffmpeg_version: '3.4' }
